// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P2Server.Misc;

namespace P2Server.Misc.Migrations
{
    [DbContext(typeof(Database))]
    partial class DatabaseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("P2Server.Model.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "The fastest car",
                            Image = "Images/car.jpg",
                            Name = "Car",
                            Price = 100.0
                        },
                        new
                        {
                            Id = 2,
                            Description = "High quality PC gaming",
                            Image = "Images/pc.jpg",
                            Name = "PC Gaming",
                            Price = 50.25
                        },
                        new
                        {
                            Id = 3,
                            Description = "The smartest phone ever",
                            Image = "Images/phone.jpg",
                            Name = "Smartphone",
                            Price = 30.149999999999999
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
